# Generated by Django 3.2.5 on 2021-08-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название проекта')),
                ('repository_link', models.URLField(verbose_name='Адрес репозитория')),
                ('description', models.TextField(blank=True, max_length=64, null=True, verbose_name='Описание проекта')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Содержимое заметки')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='Дата последнего обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Состояние заметки')),
            ],
        ),
    ]
