# Generated by Django 3.2.5 on 2021-07-26 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='author',
        ),
        migrations.AddField(
            model_name='todo',
            name='authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Автор(ы) заметки'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=64, null=True, verbose_name='Описание проекта'),
        ),
        migrations.RemoveField(
            model_name='todo',
            name='project_name',
        ),
        migrations.AddField(
            model_name='todo',
            name='project_name',
            field=models.ManyToManyField(to='todo.Project', verbose_name='Проект заметки'),
        ),
    ]
