# Generated by Django 3.2.5 on 2021-08-01 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Автор(ы) заметки'),
        ),
        migrations.AddField(
            model_name='todo',
            name='project_name',
            field=models.ManyToManyField(to='todo.Project', verbose_name='Проект заметки'),
        ),
        migrations.AddField(
            model_name='project',
            name='users_on_projects',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователей учавствуют'),
        ),
    ]
